# [opener]
# edit = [
#     { run = 'sh -c "nvim --server ~/.cache/nvim.pipe --remote \"$@\" 2>/dev/null || (rm -f ~/.cache/nvim.pipe && nvim --listen ~/.cache/nvim.pipe \"$@\")" -- "$@"', block = true, desc = "Instant LazyVim" }
# ]

# [opener]
# edit = [
#     { run = 'nvim --server "$NVIM_LISTEN_ADDRESS" --remote "$@" 2>/dev/null || nvim "$@"', block = true, desc = "Smart Open" }
# ]
# yazi 설정 예시
[opener]
edit = [
    { run = 'nvim --server $XDG_RUNTIME_DIR/nvim.sock --remote "$@" 2>/dev/null || nvim --listen $XDG_RUNTIME_DIR/nvim.sock "$@"', block = true, desc = "Instant LazyVim" }
]
# [opener]
# edit = [
#     { run = 'nv "$@"', block = true, desc = "Open in existing LazyVim" }
# ]
# 아래 내용들 테스트용이라 실제 비정상 동작함. 실행 금지.
# [opener]
# # 내가 선호하는 이미지 뷰어 직접 지명
# view_img = [
#     { run = 'swayimg "$@"', block = false, for = "unix" }
# ]
# # 시스템 설정을 따르는 기본 오프너 (XDG)
# open_xdg = [
    # { run = 'xdg-open "$@"', desc = "Open with System Default" }
# ]
#
# [open]
# rules = [
#     # 이미지는 내가 정한 swayimg로 0.1ms 만에 타격!
#     { mime = "image/*", use = "view_img" },
#     # 그 외 나머지는 모두 시스템(XDG)에게 토스!
#     { name = "*", use = "open_xdg" }
# ]
